### ISSUE TITLE
First pass at a md-menu component

### ISSUE THREAD

**Issue by DennisRoam** [justindujardin/ng2-material#24]
I didn't want to do a full PR yet but wanted to pass along my quick work with getting a menu working if anyone wants to take a look. 

menu.ts
```javascript
import {Component, ElementRef, Renderer} from 'angular2/core';
//import {Component, Directive, ElementRef, Renderer} from 'angular2/core';

@Component({
	selector: 'md-menu',
	host: {
		'(click)': 'toggle()'
    },
	template: `
		<ng-content></ng-content>
		<md-backdrop class="md-backdrop"> </md-backdrop>
	`
})
export class MdMenu {
	visible: boolean = false;
	constructor(private el: ElementRef, private renderer: Renderer) {}
	toggle() {
		this.visible = !this.visible;
		this.renderer.setElementClass(this.el.nativeElement, 'show-menu', this.visible);
	}
}
```

I couldn't get the component to load my styles, probably just an encapsulation issue but adding this SASS to my general file worked:

```css
md-menu md-menu-content {
		position: absolute;
		top:0;
		right: 0;
		box-shadow: 0px 2px 5px 0 rgba(0, 0, 0, 0.26);
    	z-index: 100;
		background: #f1f1f1;
		color: #8f8f8f;
		visibility: hidden;
		opacity: 0;
		transition: visibility 0s, opacity 0.20s linear;
		
		[md-button] {
			color: #8f8f8f !important;
    		width: 100%;
    		margin: 0;
    	}
		
}
md-menu .md-backdrop {
	display: none;
	z-index:99;
}
md-menu.show-menu md-menu-content {
	visibility: visible;
	opacity: 1;
}
md-menu.show-menu md-backdrop {
	display: block;
}
md-menu {
	position: relative;
	display: block;
}

```

And to use it:

```html
<md-menu>
        <button md-button> UserDrop </button>
        <md-menu-content>
          <button md-button (click)="user.logOut();">LogOut</button>
          <button md-button [routerLink]="['/Projects']">Projects</button>
        </md-menu-content>
 </md-menu>
```

I may flush it out with alignment and all that but for now this is ok

**Comment by justindujardin** [comment]
@DennisRoam sounds cool.  Can you create a Plunkr to show it off? Here's a template that comes preloaded with ng2-material: http://plnkr.co/edit/CnDUjVufVnevluFOBvdD?p=preview

**Comment by DennisRoam** [comment]
Sorry this took me forever to get to.
Here's my Plunker: http://plnkr.co/edit/G1f2kIEpxNzWiMhcXXP4?p=preview

Some things to note:
1. I upgraded to beta.1. I had to do this as the component renderer is different (takes native element instead of ElementRef)
2. Your plunker's css is different than the package I have. Notably the md-backdrop position:fixed.
3. The css issue was indeed viewEncapsulation but I'm lazy and didn't mess with that yet and just left the menu classes in my main scss file.

**Comment by justindujardin** [comment]
@DennisRoam very cool!  I think your component can be made a little simpler using a class binding on the host:

```typescript
//menu file. Work by Dennis Smolek for showman.io
import {Component} from 'angular2/core';

@Component({
	selector: 'md-menu',
	host: {
		'(click)': 'toggle()',
		'[class.show-menu]': 'visible'
    },
	template: `
		<ng-content></ng-content>
		<md-backdrop class="md-backdrop"> </md-backdrop>
	`
})
export class MdMenu {
	visible: boolean = false;
	toggle() {
		this.visible = !this.visible;
	}
}
```

http://plnkr.co/edit/36EGjqERGYmjMdysenxy?p=preview

**Comment by DennisRoam** [comment]
Nice! I've just started flirting with the hosts so I didn't even think of it.
What are some other features/options you think would be needed to make it usable?

**Comment by forfuns** [comment]
@DennisRoam :+1:

**Comment by tzejohn** [comment]
I was able to get the embedded styles working using the :host tag, which gets mapped to an attribute associated with the host component. This was in beta 11.

```css
md-menu:host md-menu-content {
	position: absolute;
	top:10;
	right: 0;
	box-shadow: 0px 2px 5px 0 rgba(0, 0, 0, 0.26);
	z-index: 100;
	background: #f1f1f1;
	color: #8f8f8f;
	visibility: hidden;
	opacity: 0;
	transition: visibility 0s, opacity 0.20s linear;
}

md-menu:host md-menu-content [md-button] {
	color: #8f8f8f !important;
	width: 100%;
	margin: 0;
}

md-menu:host .md-backdrop {
	display: none;
	z-index:50;
  pointer-events: auto;
}

md-menu.show-menu:host md-menu-content {
	visibility: visible;
	opacity: 1;
}

md-menu.show-menu:host md-backdrop {
	display: block;
}

md-menu:host {
	position: relative;
	display: block;
}
```

```ts
import {Component} from 'angular2/core';

@Component({
  selector: 'md-menu',
    host: {
      '(click)': 'toggle()',
      '[class.show-menu]': 'visible'
    },
  template: `
	  <ng-content></ng-content>
	  <md-backdrop class="md-backdrop"></md-backdrop>
	`,
  styleUrls: [
    './app/components/md-menu.component.css'
  ]
})
export class MdMenu {
	visible: boolean = false;
	toggle() {
		this.visible = !this.visible;
	}
}
```
